### ISSUE TITLE
How can I modify docker-compose.yml?

### ISSUE THREAD

**Issue by miraliahmadli** [ARCC-RACE/deepracer-for-dummies#39]
I was trying to train my model, but then I saw messages from my computer saying storage is not enough. 
It turns out that during training. robo folder has been created. I have splitted root and home folder and root folder has only 20gb of capacity. And now I want to create this robo folder in my home directory, therefore I changed 'Dockerfile' and I have to change 'docker-compose.yml'. But when I try to save it, it says:
`Failed to save 'docker-compose.yml': Insufficient permissions. Select 'Retry as Sudo' to retry as superuser.`

Changes I have made in "Dockerfile":
```
RUN mkdir ~/home/mirali/Desktop/github_files/deepracer_for_dummies/robo
RUN mkdir ~/home/mirali/Desktop/github_files/deepracer_for_dummies/robo/container
```
Changes I have made in "docker-compose.yml":
```
  rl_coach:
    image: aschu/rl_coach
    env_file: .env
    container_name: rl_coach
    volumes:
    - '//var/run/docker.sock:/var/run/docker.sock'
    - '../deepracer/sagemaker-python-sdk:/deepracer/sagemaker-python-sdk'
    - '../deepracer/rl_coach:/deepracer/rl_coach'
    - '../robo/container:/robo/container'
    depends_on:
    - minio
```

Did I correctly to edit both files and which permission do I need to make changes to docker-compose.yml?
